# version: "3.9"

services:
  flightmare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flightmare_sim
    # environment:
      # - DISPLAY=${DISPLAY}
      # - QT_X11_NO_MITSHM=1
      # - ROS_DISTRO=noetic
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix  # Allow GUI
    #   - ./catkin_ws:/home/catkin_ws    # Optional: mount workspace
    # devices:
    #   - /dev/dri:/dev/dri              # For hardware acceleration (OpenGL)
    network_mode: host                 # Optional for ROS networking
    stdin_open: true                   # Enable interactive shell (like -i)
    tty: true                          # Enable terminal (like -t)
    # ports:
    #   - 8080:8080
    command: [ "/bin/bash", "-c", 
              "source /home/catkin_ws/devel/setup.bash && roslaunch flightros photon_gazebo.launch" ]
